<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.1.0 ./static/models/tshirt.glb --transform
Author: Tabbuso (https://sketchfab.com/Tabbuso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-5a21282b2e454d1696547148f617d3d0
Title: Tshirt
-->

<script lang="ts">
	import type { Snippet } from 'svelte';
	import { T } from '@threlte/core';
	import { useGltf, useDraco } from '@threlte/extras';

	type Props = {
		fallback?: Snippet;
		error?: Snippet<[{ error: unknown }]>;
		children?: Snippet<[{ ref: any }]>;
		ref?: any;
		[key: string]: any;
	};

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props = $props();

	const gltf = useGltf('/models/tshirt.gltf', {
		dracoLoader: useDraco()
	});
</script>

<T.Group
	bind:ref
	dispose={false}
	{...props}
>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			material={gltf.materials.FABRIC_1_FRONT_4193}
			rotation={[Math.PI / 2, 0, 0]}
			scale={0.04}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>